# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d86508fa710a25e4defec74f55607698e54b4e127bf9e4a212e888737825dceb98e56843a5be458e6fd003a5f9beef91146c6a749e8e58a3fc88222357519685

test:
  secret_key_base: 8f4fcb23a74dd50bac8fcf33695a080ba7fcaa329c48b8077d198b774a2a2c89456567346f8c69a14baa663a27006c36f0f3734d0c04a6b197e8d1aefd96b013

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
